name: Build and deploy React app to Azure Web App

on:
  push:
    branches:
      - main # Change this to your default branch

env:
  AZURE_WEBAPP_NAME: TradesPro # Replace with your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: ./build # Path to the React build folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use a stable Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-app
          path: ./build # Ensure this matches the actual build folder

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: react-app
          path: ./build # Ensure this matches the artifact path

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ./build # Ensure this matches the downloaded artifact path