name: Deploy React App to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: TradesPro
  AZURE_WEBAPP_PACKAGE_PATH: 'build'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install dependencies
      run: npm install
      
    - name: Build React app
      run: npm run build
      
    - name: Zip the build files
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        zip -r ../build.zip *
        cd ..
      
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: build.zip
        # Add these important settings:
        slot-name: production  # or your slot name if using deployment slots
        clean: true  # Cleans the target directory before deployment